### ISSUE TITLE
Put the WebSocket API behind a CloudFront distro

### ISSUE THREAD

**Issue by douglasnaphas** [dan-muller/room-app#1]
That way the frontend doesn't need to know any domain names, it can just make a websocket connection to /prod/.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-working-with.websockets.html

**Comment by douglasnaphas** [comment]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html

**Comment by douglasnaphas** [comment]
This shows adding a CloudFront behavior for a REST API:

https://github.com/cdk-turnkey/brian-liberation/blob/master/lib/madliberation-webapp.ts#L371-L390

**Comment by douglasnaphas** [comment]
We’re getting HTTP 426 Upgrade Required when we try to connect to a WebSocket through CloudFront.

I wonder if some header needs to be in the response from CloudFront, and it’s missing.

To investigate this, we can:
1. Turn on CloudFront access logging to try to get a better view of the headers going from the viewer to CloudFront, and from CloudFront to the API Gateway origin.
2. Try to make a connection in the browser to the WebSocket API Gateway. Assuming it still works, we can then compare the headers sent and received in each case.

Maybe we need to explicitly include the missing headers (if there are any missing) from CloudFront using CloudFront functions or Lambda@Edge.

**Comment by douglasnaphas** [comment]
On the left is a request that successfully made a WebSocket connection. On the right is one that gave HTTP 426.

It does look from this like CloudFront omitted some headers.

<img width="1680" alt="Screen Shot 2021-06-13 at 8 11 59 PM" src="https://user-images.githubusercontent.com/5433410/121826133-40cf2a00-cc84-11eb-9dc1-b19aead17151.png">


There's also some chatter (https://forums.aws.amazon.com/thread.jspa?messageID=883536&tstart=0 and https://stackoverflow.com/questions/56537682/aws-api-gateway-websocket-chrome-error-during-websocket-handshake-sent-non-e) about missing WebSocket-related headers.

This [WebSocket Requirements](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-working-with.websockets.html) doc also makes it sound like the `sec-websocket-accept` response header, which is missing from our failed response, is required, along with others.

<img width="1291" alt="Screen Shot 2021-06-13 at 8 14 47 PM" src="https://user-images.githubusercontent.com/5433410/121826131-3b71df80-cc84-11eb-9221-f09ffb3e2b1e.png">

**Comment by douglasnaphas** [comment]
[This](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-headers-behavior) says, regarding CloudFront's treatment of the incoming (viewer to CloudFront) Upgrade request header:

> Upgrade | CloudFront removes the header, unless you've established a WebSocket connection.

This raises the question: how do I establish a WebSocket connection?

<img width="936" alt="Screen Shot 2021-06-13 at 8 29 45 PM" src="https://user-images.githubusercontent.com/5433410/121826536-272ee200-cc86-11eb-9251-5e8b38a1e4ab.png">

**Comment by douglasnaphas** [comment]
Quick note: I believe the 426 only showed up in Firefox, in my testing. It still didn't work with CloudFront in Chrome--it just didn't show me a status code or response headers.

**Comment by dan-muller** [comment]
This looks like this issue is completed as of the merging of #2. I am going to close this issue.
